# Complete Stockly asset database
# DAX40, S&P500, NASDAQ100, Gaming, Biotech, Finance, EUROSTOXX50, UK, Swiss, Nordic, MDAX,
# top ETFs, top cryptos, commodities

ASSETS = [
    # ── DAX 40 ──────────────────────────────────────────────────────────────────
    {"ticker":"ADS.DE",  "name":"Adidas AG",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"AIR.DE",  "name":"Airbus SE",               "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"ALV.DE",  "name":"Allianz SE",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"BAS.DE",  "name":"BASF SE",                 "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"BAYN.DE", "name":"Bayer AG",                "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"BEI.DE",  "name":"Beiersdorf AG",           "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"BMW.DE",  "name":"BMW AG",                  "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"BNR.DE",  "name":"Brenntag SE",             "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"CBK.DE",  "name":"Commerzbank AG",          "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"CON.DE",  "name":"Continental AG",          "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"1COV.DE", "name":"Covestro AG",             "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"DB1.DE",  "name":"Deutsche Börse AG",       "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"DBK.DE",  "name":"Deutsche Bank AG",        "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"DPW.DE",  "name":"Deutsche Post AG",        "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"DTE.DE",  "name":"Deutsche Telekom AG",     "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"DTG.DE",  "name":"Daimler Truck Holding",   "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"ENR.DE",  "name":"Siemens Energy AG",       "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"EOAN.DE", "name":"E.ON SE",                 "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"FRE.DE",  "name":"Fresenius SE",            "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"FME.DE",  "name":"Fresenius Medical Care",  "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"HEI.DE",  "name":"Heidelberg Materials",    "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"HEN3.DE", "name":"Henkel AG",               "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"HNR1.DE", "name":"Hannover Rück SE",        "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"IFX.DE",  "name":"Infineon Technologies",   "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"LHA.DE",  "name":"Deutsche Lufthansa AG",   "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"LIN",     "name":"Linde plc",               "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"MBG.DE",  "name":"Mercedes-Benz Group",     "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"MRK.DE",  "name":"Merck KGaA",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"MTX.DE",  "name":"MTU Aero Engines",        "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"MUV2.DE", "name":"Munich Re",               "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"P911.DE", "name":"Porsche AG",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"PAH3.DE", "name":"Porsche SE",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"QIA.DE",  "name":"Qiagen NV",               "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"RHM.DE",  "name":"Rheinmetall AG",          "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"RWE.DE",  "name":"RWE AG",                  "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"SAP.DE",  "name":"SAP SE",                  "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"SHL.DE",  "name":"Siemens Healthineers",    "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"SIE.DE",  "name":"Siemens AG",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"SRT3.DE", "name":"Sartorius AG",            "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"SY1.DE",  "name":"Symrise AG",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"VNA.DE",  "name":"Vonovia SE",              "type":"stock","category":"DAX40","region":"DE"},
    {"ticker":"VOW3.DE", "name":"Volkswagen AG",           "type":"stock","category":"DAX40","region":"DE"},

    # ── MDAX & German stocks ─────────────────────────────────────────────────────
    {"ticker":"ZAL.DE",  "name":"Zalando SE",             "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"DHER.DE", "name":"Delivery Hero SE",        "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"PUM.DE",  "name":"Puma SE",                 "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"FRA.DE",  "name":"Fraport AG",              "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"KBX.DE",  "name":"Knorr-Bremse AG",        "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"NEM.DE",  "name":"Nemetschek SE",           "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"AFX.DE",  "name":"Carl Zeiss Meditec AG",  "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"LEO.DE",  "name":"LANXESS AG",              "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"SDF.DE",  "name":"K+S AG",                  "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"TMV.DE",  "name":"TeamViewer AG",           "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"WAF.DE",  "name":"Siltronic AG",            "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"EVK.DE",  "name":"Evonik Industries AG",    "type":"stock","category":"MDAX","region":"DE"},
    {"ticker":"GXI.DE",  "name":"Gerresheimer AG",         "type":"stock","category":"MDAX","region":"DE"},

    # ── S&P 500 – Blue Chips ─────────────────────────────────────────────────────
    {"ticker":"AAPL",  "name":"Apple Inc.",                "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MSFT",  "name":"Microsoft Corporation",     "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"NVDA",  "name":"NVIDIA Corporation",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"AMZN",  "name":"Amazon.com Inc.",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"META",  "name":"Meta Platforms Inc.",       "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"GOOGL", "name":"Alphabet Inc. (A)",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"GOOG",  "name":"Alphabet Inc. (C)",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"TSLA",  "name":"Tesla Inc.",                "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BRK-B", "name":"Berkshire Hathaway B",      "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"UNH",   "name":"UnitedHealth Group",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"JNJ",   "name":"Johnson & Johnson",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"JPM",   "name":"JPMorgan Chase",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"XOM",   "name":"Exxon Mobil",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"V",     "name":"Visa Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PG",    "name":"Procter & Gamble",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MA",    "name":"Mastercard Inc.",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"HD",    "name":"Home Depot",                "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CVX",   "name":"Chevron Corporation",       "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MRK",   "name":"Merck & Co.",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ABBV",  "name":"AbbVie Inc.",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PFE",   "name":"Pfizer Inc.",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"KO",    "name":"Coca-Cola Company",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"AVGO",  "name":"Broadcom Inc.",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PEP",   "name":"PepsiCo Inc.",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"COST",  "name":"Costco Wholesale",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"TMO",   "name":"Thermo Fisher Scientific",  "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ADBE",  "name":"Adobe Inc.",                "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"AMD",   "name":"Advanced Micro Devices",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ORCL",  "name":"Oracle Corporation",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CSCO",  "name":"Cisco Systems",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ACN",   "name":"Accenture plc",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MCD",   "name":"McDonald's Corporation",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ABT",   "name":"Abbott Laboratories",       "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"NFLX",  "name":"Netflix Inc.",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"DIS",   "name":"Walt Disney Company",       "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CRM",   "name":"Salesforce Inc.",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"LLY",   "name":"Eli Lilly and Company",     "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"INTC",  "name":"Intel Corporation",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"NKE",   "name":"Nike Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"WMT",   "name":"Walmart Inc.",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"VZ",    "name":"Verizon Communications",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PYPL",  "name":"PayPal Holdings",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BAC",   "name":"Bank of America",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"GS",    "name":"Goldman Sachs",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"UBER",  "name":"Uber Technologies",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"COIN",  "name":"Coinbase Global",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PLTR",  "name":"Palantir Technologies",     "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SHOP",  "name":"Shopify Inc.",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SQ",    "name":"Block Inc.",                "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SNOW",  "name":"Snowflake Inc.",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SPOT",  "name":"Spotify Technology",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"HOOD",  "name":"Robinhood Markets",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"RBLX",  "name":"Roblox Corporation",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ABNB",  "name":"Airbnb Inc.",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"LYFT",  "name":"Lyft Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PINS",  "name":"Pinterest Inc.",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SNAP",  "name":"Snap Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"Z",     "name":"Zillow Group",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ROKU",  "name":"Roku Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"RIVN",  "name":"Rivian Automotive",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"LCID",  "name":"Lucid Group",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"DXCM",  "name":"DexCom Inc.",               "type":"stock","category":"S&P500","region":"US"},

    # ── S&P 500 – Finance & Banking ──────────────────────────────────────────────
    {"ticker":"AXP",   "name":"American Express",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MS",    "name":"Morgan Stanley",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"C",     "name":"Citigroup Inc.",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"WFC",   "name":"Wells Fargo",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BLK",   "name":"BlackRock Inc.",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SCHW",  "name":"Charles Schwab",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"USB",   "name":"U.S. Bancorp",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PNC",   "name":"PNC Financial Services",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CME",   "name":"CME Group",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ICE",   "name":"Intercontinental Exchange", "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SPGI",  "name":"S&P Global Inc.",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MCO",   "name":"Moody's Corporation",       "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BX",    "name":"Blackstone Inc.",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"KKR",   "name":"KKR & Co.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"TFC",   "name":"Truist Financial",          "type":"stock","category":"S&P500","region":"US"},

    # ── S&P 500 – Gaming & Entertainment ────────────────────────────────────────
    {"ticker":"TTWO",  "name":"Take-Two Interactive",      "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"EA",    "name":"Electronic Arts",           "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"U",     "name":"Unity Software",            "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"GME",   "name":"GameStop Corp.",            "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"NTDOY", "name":"Nintendo Co. ADR",          "type":"stock","category":"Gaming","region":"ASIA"},
    {"ticker":"SONY",  "name":"Sony Group Corp. ADR",      "type":"stock","category":"Gaming","region":"ASIA"},
    {"ticker":"PLTK",  "name":"Playtika Holding",          "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"SKLZ",  "name":"Skillz Inc.",               "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"GLXG",  "name":"Galaxy Gaming",             "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"PARA",  "name":"Paramount Global",          "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"WBD",   "name":"Warner Bros. Discovery",    "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"CMCSA", "name":"Comcast Corporation",       "type":"stock","category":"Gaming","region":"US"},
    {"ticker":"T",     "name":"AT&T Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CHTR",  "name":"Charter Communications",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"FOXA",  "name":"Fox Corporation",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"IMAX",  "name":"IMAX Corporation",          "type":"stock","category":"Gaming","region":"US"},

    # ── S&P 500 – Biotech & Pharma ───────────────────────────────────────────────
    {"ticker":"MRNA",  "name":"Moderna Inc.",              "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"BNTX",  "name":"BioNTech SE ADR",           "type":"stock","category":"Biotech","region":"EU"},
    {"ticker":"REGN",  "name":"Regeneron Pharmaceuticals", "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"GILD",  "name":"Gilead Sciences",           "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"BIIB",  "name":"Biogen Inc.",               "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"VRTX",  "name":"Vertex Pharmaceuticals",    "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"BMY",   "name":"Bristol-Myers Squibb",      "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"AMGN",  "name":"Amgen Inc.",                "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"AZN",   "name":"AstraZeneca ADR",           "type":"stock","category":"Biotech","region":"EU"},
    {"ticker":"BSX",   "name":"Boston Scientific",         "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"MDT",   "name":"Medtronic plc",             "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"SYK",   "name":"Stryker Corporation",       "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"ISRG",  "name":"Intuitive Surgical",        "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"EW",    "name":"Edwards Lifesciences",      "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"RMD",   "name":"ResMed Inc.",               "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"HOLX",  "name":"Hologic Inc.",              "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"HUM",   "name":"Humana Inc.",               "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"CI",    "name":"Cigna Group",               "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"CVS",   "name":"CVS Health Corporation",    "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"ZBH",   "name":"Zimmer Biomet Holdings",    "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"BAX",   "name":"Baxter International",      "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"IQV",   "name":"IQVIA Holdings",            "type":"stock","category":"Biotech","region":"US"},
    {"ticker":"ALNY",  "name":"Alnylam Pharmaceuticals",   "type":"stock","category":"Biotech","region":"US"},

    # ── S&P 500 – Consumer & Retail ──────────────────────────────────────────────
    {"ticker":"SBUX",  "name":"Starbucks Corporation",     "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"TGT",   "name":"Target Corporation",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"LOW",   "name":"Lowe's Companies",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"TJX",   "name":"TJX Companies",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"EBAY",  "name":"eBay Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ETSY",  "name":"Etsy Inc.",                 "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"WBA",   "name":"Walgreens Boots Alliance",  "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BBY",   "name":"Best Buy Co.",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ULTA",  "name":"Ulta Beauty",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ROST",  "name":"Ross Stores",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"DLTR",  "name":"Dollar Tree Inc.",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CMG",   "name":"Chipotle Mexican Grill",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"YUM",   "name":"Yum! Brands Inc.",          "type":"stock","category":"S&P500","region":"US"},

    # ── S&P 500 – Airlines & Travel ──────────────────────────────────────────────
    {"ticker":"DAL",   "name":"Delta Air Lines",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"UAL",   "name":"United Airlines Holdings",  "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"AAL",   "name":"American Airlines Group",   "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"LUV",   "name":"Southwest Airlines",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MAR",   "name":"Marriott International",    "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"HLT",   "name":"Hilton Worldwide",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CCL",   "name":"Carnival Corporation",      "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"RCL",   "name":"Royal Caribbean Group",     "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BKNG",  "name":"Booking Holdings",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"EXPE",  "name":"Expedia Group",             "type":"stock","category":"S&P500","region":"US"},

    # ── S&P 500 – Energy ─────────────────────────────────────────────────────────
    {"ticker":"OXY",   "name":"Occidental Petroleum",      "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SLB",   "name":"SLB (Schlumberger)",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"HAL",   "name":"Halliburton Company",       "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"NEE",   "name":"NextEra Energy",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"DUK",   "name":"Duke Energy Corporation",   "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"SO",    "name":"Southern Company",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"AEP",   "name":"American Electric Power",   "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PSX",   "name":"Phillips 66",               "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"VLO",   "name":"Valero Energy",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MPC",   "name":"Marathon Petroleum",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"EOG",   "name":"EOG Resources",             "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"COP",   "name":"ConocoPhillips",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"BKR",   "name":"Baker Hughes Company",      "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"KMI",   "name":"Kinder Morgan",             "type":"stock","category":"S&P500","region":"US"},

    # ── S&P 500 – Industrials & Defense ─────────────────────────────────────────
    {"ticker":"BA",    "name":"Boeing Company",            "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"RTX",   "name":"RTX Corporation (Raytheon)","type":"stock","category":"S&P500","region":"US"},
    {"ticker":"LMT",   "name":"Lockheed Martin",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"NOC",   "name":"Northrop Grumman",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"GD",    "name":"General Dynamics",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"HON",   "name":"Honeywell International",   "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"GE",    "name":"GE Aerospace",              "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"CAT",   "name":"Caterpillar Inc.",          "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"DE",    "name":"Deere & Company",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"UPS",   "name":"United Parcel Service",     "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"FDX",   "name":"FedEx Corporation",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MMM",   "name":"3M Company",                "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"EMR",   "name":"Emerson Electric Co.",      "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"ETN",   "name":"Eaton Corporation",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"PH",    "name":"Parker-Hannifin Corporation","type":"stock","category":"S&P500","region":"US"},
    {"ticker":"GWW",   "name":"W.W. Grainger",             "type":"stock","category":"S&P500","region":"US"},

    # ── S&P 500 – More Tech ──────────────────────────────────────────────────────
    {"ticker":"ARM",   "name":"ARM Holdings plc ADR",      "type":"stock","category":"NASDAQ100","region":"EU"},
    {"ticker":"ANET",  "name":"Arista Networks",           "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"IBM",   "name":"IBM Corporation",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"HPQ",   "name":"HP Inc.",                   "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"DELL",  "name":"Dell Technologies",         "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"WDC",   "name":"Western Digital",           "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"STX",   "name":"Seagate Technology",        "type":"stock","category":"S&P500","region":"US"},
    {"ticker":"MRVL",  "name":"Marvell Technology",        "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"ON",    "name":"ON Semiconductor",          "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"SMCI",  "name":"Super Micro Computer",      "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"FTNT",  "name":"Fortinet Inc.",             "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"ZM",    "name":"Zoom Video Communications", "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"TEAM",  "name":"Atlassian Corporation",     "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"HUBS",  "name":"HubSpot Inc.",              "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"NOW",   "name":"ServiceNow Inc.",           "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"WDAY",  "name":"Workday Inc.",              "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"VEEV",  "name":"Veeva Systems",             "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"TTD",   "name":"The Trade Desk",            "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"DOCU",  "name":"DocuSign Inc.",             "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"TWLO",  "name":"Twilio Inc.",               "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"MDB",   "name":"MongoDB Inc.",              "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"NTNX",  "name":"Nutanix Inc.",              "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"ESTC",  "name":"Elastic NV",               "type":"stock","category":"NASDAQ100","region":"US"},

    # ── REITs ────────────────────────────────────────────────────────────────────
    {"ticker":"AMT",   "name":"American Tower Corp.",      "type":"stock","category":"REITs","region":"US"},
    {"ticker":"PLD",   "name":"Prologis Inc.",             "type":"stock","category":"REITs","region":"US"},
    {"ticker":"CCI",   "name":"Crown Castle Inc.",         "type":"stock","category":"REITs","region":"US"},
    {"ticker":"EQIX",  "name":"Equinix Inc.",              "type":"stock","category":"REITs","region":"US"},
    {"ticker":"SPG",   "name":"Simon Property Group",      "type":"stock","category":"REITs","region":"US"},
    {"ticker":"O",     "name":"Realty Income Corporation", "type":"stock","category":"REITs","region":"US"},
    {"ticker":"WELL",  "name":"Welltower Inc.",            "type":"stock","category":"REITs","region":"US"},
    {"ticker":"PSA",   "name":"Public Storage",            "type":"stock","category":"REITs","region":"US"},
    {"ticker":"DLR",   "name":"Digital Realty Trust",      "type":"stock","category":"REITs","region":"US"},

    # ── NASDAQ 100 Extra ─────────────────────────────────────────────────────────
    {"ticker":"ASML",  "name":"ASML Holding",             "type":"stock","category":"NASDAQ100","region":"EU"},
    {"ticker":"TSM",   "name":"Taiwan Semiconductor",      "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"QCOM",  "name":"Qualcomm Inc.",             "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"TXN",   "name":"Texas Instruments",         "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"AMAT",  "name":"Applied Materials",         "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"MU",    "name":"Micron Technology",         "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"LRCX",  "name":"Lam Research",             "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"KLAC",  "name":"KLA Corporation",           "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"PANW",  "name":"Palo Alto Networks",        "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"CRWD",  "name":"CrowdStrike Holdings",      "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"DDOG",  "name":"Datadog Inc.",              "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"ZS",    "name":"Zscaler Inc.",              "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"OKTA",  "name":"Okta Inc.",                 "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"NET",   "name":"Cloudflare Inc.",           "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"MELI",  "name":"MercadoLibre Inc.",         "type":"stock","category":"NASDAQ100","region":"US"},
    {"ticker":"SE",    "name":"Sea Limited",               "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"BABA",  "name":"Alibaba Group",             "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"JD",    "name":"JD.com Inc.",               "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"PDD",   "name":"PDD Holdings",              "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"NIO",   "name":"NIO Inc.",                  "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"XPEV",  "name":"XPeng Inc.",                "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"LI",    "name":"Li Auto Inc.",              "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"BIDU",  "name":"Baidu Inc.",                "type":"stock","category":"NASDAQ100","region":"ASIA"},
    {"ticker":"TMUS",  "name":"T-Mobile US Inc.",          "type":"stock","category":"NASDAQ100","region":"US"},

    # ── EURO STOXX 50 ────────────────────────────────────────────────────────────
    {"ticker":"ASML.AS","name":"ASML Holding NV",         "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"MC.PA",  "name":"LVMH Moët Hennessy",      "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"OR.PA",  "name":"L'Oréal SA",              "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"SAN.PA", "name":"Sanofi SA",               "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"TTE.PA", "name":"TotalEnergies SE",        "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"BNP.PA", "name":"BNP Paribas SA",          "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"SU.PA",  "name":"Schneider Electric",      "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"AI.PA",  "name":"Air Liquide SA",          "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"CS.PA",  "name":"AXA SA",                  "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"DG.PA",  "name":"Vinci SA",                "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"ITX.MC", "name":"Inditex SA",              "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"SAN.MC", "name":"Banco Santander",         "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"BBVA.MC","name":"BBVA",                    "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"IBE.MC", "name":"Iberdrola SA",            "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"ENEL.MI","name":"Enel SpA",                "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"ENI.MI", "name":"Eni SpA",                 "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"ISP.MI", "name":"Intesa Sanpaolo",         "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"UCG.MI", "name":"UniCredit SpA",           "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"STLA.MI","name":"Stellantis NV",           "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"INGA.AS","name":"ING Groep NV",            "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"PHIA.AS","name":"Philips NV",              "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"AD.AS",  "name":"Ahold Delhaize",          "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"ACA.PA", "name":"Crédit Agricole SA",      "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"GLE.PA", "name":"Société Générale SA",     "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"STM.PA", "name":"STMicroelectronics NV",   "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"KER.PA", "name":"Kering SA",               "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"RI.PA",  "name":"Pernod Ricard SA",        "type":"stock","category":"EUROSTOXX50","region":"EU"},
    {"ticker":"DSM.AS", "name":"DSM-Firmenich AG",        "type":"stock","category":"EUROSTOXX50","region":"EU"},

    # ── UK Stocks ────────────────────────────────────────────────────────────────
    {"ticker":"AZN.L",  "name":"AstraZeneca plc",         "type":"stock","category":"UK","region":"EU"},
    {"ticker":"SHEL.L", "name":"Shell plc",               "type":"stock","category":"UK","region":"EU"},
    {"ticker":"BP.L",   "name":"BP plc",                  "type":"stock","category":"UK","region":"EU"},
    {"ticker":"ULVR.L", "name":"Unilever plc",            "type":"stock","category":"UK","region":"EU"},
    {"ticker":"RIO.L",  "name":"Rio Tinto plc",           "type":"stock","category":"UK","region":"EU"},
    {"ticker":"GSK.L",  "name":"GSK plc",                 "type":"stock","category":"UK","region":"EU"},
    {"ticker":"HSBA.L", "name":"HSBC Holdings plc",       "type":"stock","category":"UK","region":"EU"},
    {"ticker":"LLOY.L", "name":"Lloyds Banking Group",    "type":"stock","category":"UK","region":"EU"},
    {"ticker":"BARC.L", "name":"Barclays plc",            "type":"stock","category":"UK","region":"EU"},
    {"ticker":"VOD.L",  "name":"Vodafone Group plc",      "type":"stock","category":"UK","region":"EU"},
    {"ticker":"BT-A.L", "name":"BT Group plc",            "type":"stock","category":"UK","region":"EU"},
    {"ticker":"DGE.L",  "name":"Diageo plc",              "type":"stock","category":"UK","region":"EU"},
    {"ticker":"REL.L",  "name":"RELX plc",                "type":"stock","category":"UK","region":"EU"},
    {"ticker":"SGE.L",  "name":"Sage Group plc",          "type":"stock","category":"UK","region":"EU"},
    {"ticker":"AAL.L",  "name":"Anglo American plc",      "type":"stock","category":"UK","region":"EU"},

    # ── Swiss Stocks ─────────────────────────────────────────────────────────────
    {"ticker":"ROG.SW",  "name":"Roche Holding AG",       "type":"stock","category":"CH","region":"EU"},
    {"ticker":"NESN.SW", "name":"Nestlé SA",              "type":"stock","category":"CH","region":"EU"},
    {"ticker":"NOVN.SW", "name":"Novartis AG",            "type":"stock","category":"CH","region":"EU"},
    {"ticker":"LONN.SW", "name":"Lonza Group AG",         "type":"stock","category":"CH","region":"EU"},
    {"ticker":"UBSG.SW", "name":"UBS Group AG",           "type":"stock","category":"CH","region":"EU"},
    {"ticker":"CFR.SW",  "name":"Richemont SA",           "type":"stock","category":"CH","region":"EU"},
    {"ticker":"ZURN.SW", "name":"Zurich Insurance Group", "type":"stock","category":"CH","region":"EU"},
    {"ticker":"SREN.SW", "name":"Swiss Re AG",            "type":"stock","category":"CH","region":"EU"},
    {"ticker":"ABBN.SW", "name":"ABB Ltd",                "type":"stock","category":"CH","region":"EU"},
    {"ticker":"KRON.SW", "name":"Kuehne+Nagel International","type":"stock","category":"CH","region":"EU"},
    {"ticker":"GEBN.SW", "name":"Geberit AG",             "type":"stock","category":"CH","region":"EU"},
    {"ticker":"GIVN.SW", "name":"Givaudan SA",            "type":"stock","category":"CH","region":"EU"},

    # ── Nordic Stocks ────────────────────────────────────────────────────────────
    {"ticker":"NOVO-B.CO","name":"Novo Nordisk A/S",      "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"ORSTED.CO","name":"Ørsted A/S",            "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"VOLV-B.ST","name":"Volvo AB (B-Aktien)",   "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"ERIC-B.ST","name":"Ericsson AB (B)",       "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"ATCO-A.ST","name":"Atlas Copco AB (A)",    "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"SAND.ST",  "name":"Sandvik AB",            "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"HEXA-B.ST","name":"Hexagon AB (B)",        "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"SEB-A.ST", "name":"SEB AB (A)",            "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"SWMA.ST",  "name":"Swedish Match AB",      "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"NOKIA.HE", "name":"Nokia Oyj",             "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"SAMPO.HE", "name":"Sampo Oyj",             "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"NESTE.HE", "name":"Neste Oyj",             "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"EQNR",     "name":"Equinor ASA ADR",       "type":"stock","category":"Nordic","region":"EU"},
    {"ticker":"NHY.OL",   "name":"Norsk Hydro ASA",       "type":"stock","category":"Nordic","region":"EU"},

    # ── Top ETFs ─────────────────────────────────────────────────────────────────
    {"ticker":"SPY",     "name":"SPDR S&P 500 ETF",            "type":"etf","category":"ETF","region":"US"},
    {"ticker":"QQQ",     "name":"Invesco NASDAQ 100 ETF",      "type":"etf","category":"ETF","region":"US"},
    {"ticker":"VOO",     "name":"Vanguard S&P 500 ETF",        "type":"etf","category":"ETF","region":"US"},
    {"ticker":"VTI",     "name":"Vanguard Total Market ETF",   "type":"etf","category":"ETF","region":"US"},
    {"ticker":"IVV",     "name":"iShares Core S&P 500 ETF",   "type":"etf","category":"ETF","region":"US"},
    {"ticker":"VEA",     "name":"Vanguard Developed Markets ETF","type":"etf","category":"ETF","region":"US"},
    {"ticker":"VWO",     "name":"Vanguard Emerging Markets ETF","type":"etf","category":"ETF","region":"US"},
    {"ticker":"GLD",     "name":"SPDR Gold Trust",             "type":"etf","category":"ETF","region":"US"},
    {"ticker":"SLV",     "name":"iShares Silver Trust",        "type":"etf","category":"ETF","region":"US"},
    {"ticker":"ARKK",    "name":"ARK Innovation ETF",          "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLC",     "name":"Communication Services ETF",  "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLK",     "name":"Technology Select ETF",       "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLF",     "name":"Financial Select ETF",        "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLE",     "name":"Energy Select ETF",           "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLV",     "name":"Health Care Select ETF",      "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLI",     "name":"Industrial Select ETF",       "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLY",     "name":"Consumer Discretionary ETF",  "type":"etf","category":"ETF","region":"US"},
    {"ticker":"XLP",     "name":"Consumer Staples ETF",        "type":"etf","category":"ETF","region":"US"},
    {"ticker":"SOXX",    "name":"iShares Semiconductor ETF",   "type":"etf","category":"ETF","region":"US"},
    {"ticker":"TLT",     "name":"iShares 20+ Year Treasury ETF","type":"etf","category":"ETF","region":"US"},
    {"ticker":"HYG",     "name":"iShares High Yield Corp Bond ETF","type":"etf","category":"ETF","region":"US"},
    {"ticker":"EUNL.DE", "name":"iShares Core MSCI World",    "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"VWCE.DE", "name":"Vanguard FTSE All-World",    "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"EXXT.DE", "name":"iShares NASDAQ-100 (DE)",    "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"EXS1.DE", "name":"iShares Core DAX",           "type":"etf","category":"ETF","region":"DE"},
    {"ticker":"XDWD.DE", "name":"Xtrackers MSCI World",       "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"IEMM.AS", "name":"iShares MSCI EM IMI",        "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"CSPX.AS", "name":"iShares Core S&P 500 (EUR)", "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"VUSA.AS", "name":"Vanguard S&P 500 (EUR)",     "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"VGWL.DE", "name":"Vanguard FTSE Developed World","type":"etf","category":"ETF","region":"EU"},
    {"ticker":"SPYW.DE", "name":"SPDR S&P 500 EUR Hdgd ETF",  "type":"etf","category":"ETF","region":"EU"},
    {"ticker":"UUP",     "name":"Invesco DB US Dollar ETF",   "type":"etf","category":"ETF","region":"US"},

    # ── Kryptos ──────────────────────────────────────────────────────────────────
    {"ticker":"BTC-USD",  "name":"Bitcoin",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ETH-USD",  "name":"Ethereum",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"BNB-USD",  "name":"BNB",                   "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"SOL-USD",  "name":"Solana",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"XRP-USD",  "name":"XRP",                   "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"USDC-USD", "name":"USD Coin",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ADA-USD",  "name":"Cardano",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"AVAX-USD", "name":"Avalanche",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"DOGE-USD", "name":"Dogecoin",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"DOT-USD",  "name":"Polkadot",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"MATIC-USD","name":"Polygon",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"LINK-USD", "name":"Chainlink",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"SHIB-USD", "name":"Shiba Inu",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"LTC-USD",  "name":"Litecoin",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"UNI-USD",  "name":"Uniswap",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ATOM-USD", "name":"Cosmos",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"XLM-USD",  "name":"Stellar",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ALGO-USD", "name":"Algorand",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"VET-USD",  "name":"VeChain",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ICP-USD",  "name":"Internet Computer",     "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"FIL-USD",  "name":"Filecoin",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ETC-USD",  "name":"Ethereum Classic",      "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"NEAR-USD", "name":"NEAR Protocol",         "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"APT-USD",  "name":"Aptos",                 "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ARB-USD",  "name":"Arbitrum",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"OP-USD",   "name":"Optimism",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"INJ-USD",  "name":"Injective",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"SUI-USD",  "name":"Sui",                   "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"SEI-USD",  "name":"Sei",                   "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"TIA-USD",  "name":"Celestia",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"JUP-USD",  "name":"Jupiter",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"WIF-USD",  "name":"dogwifhat",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"PEPE-USD", "name":"Pepe",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"BONK-USD", "name":"Bonk",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"FTM-USD",  "name":"Fantom",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"SAND-USD", "name":"The Sandbox",           "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"MANA-USD", "name":"Decentraland",          "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"AXS-USD",  "name":"Axie Infinity",         "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"GRT-USD",  "name":"The Graph",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"MKR-USD",  "name":"Maker",                 "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"AAVE-USD", "name":"Aave",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"CRV-USD",  "name":"Curve DAO Token",       "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"SNX-USD",  "name":"Synthetix",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"LDO-USD",  "name":"Lido DAO",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"RPL-USD",  "name":"Rocket Pool",           "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"RUNE-USD", "name":"THORChain",             "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"KAVA-USD", "name":"Kava",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ROSE-USD", "name":"Oasis Network",         "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"FLOW-USD", "name":"Flow",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"HNT-USD",  "name":"Helium",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"AR-USD",   "name":"Arweave",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"EGLD-USD", "name":"MultiversX",            "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"XTZ-USD",  "name":"Tezos",                 "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"EOS-USD",  "name":"EOS",                   "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"IOTA-USD", "name":"IOTA",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ZEC-USD",  "name":"Zcash",                 "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"DASH-USD", "name":"Dash",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"BAT-USD",  "name":"Basic Attention Token", "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"ENJ-USD",  "name":"Enjin Coin",            "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"CHZ-USD",  "name":"Chiliz",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"HOT-USD",  "name":"Holo",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"DYDX-USD", "name":"dYdX",                  "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"GMX-USD",  "name":"GMX",                   "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"STX-USD",  "name":"Stacks",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"HBAR-USD", "name":"Hedera",                "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"KAS-USD",  "name":"Kaspa",                 "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"RENDER-USD","name":"Render",               "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"FET-USD",  "name":"Fetch.ai",              "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"OCEAN-USD","name":"Ocean Protocol",        "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"AGIX-USD", "name":"SingularityNET",        "type":"crypto","category":"Krypto","region":"GLOBAL"},
    {"ticker":"POL-USD",  "name":"Polygon (POL)",         "type":"crypto","category":"Krypto","region":"GLOBAL"},

    # ── Rohstoffe ────────────────────────────────────────────────────────────────
    {"ticker":"GC=F",  "name":"Gold Futures",              "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"SI=F",  "name":"Silber Futures",            "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"CL=F",  "name":"Rohöl (WTI)",              "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"BZ=F",  "name":"Rohöl (Brent)",            "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"NG=F",  "name":"Erdgas Futures",            "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"HG=F",  "name":"Kupfer Futures",            "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"PL=F",  "name":"Platin Futures",            "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"PA=F",  "name":"Palladium Futures",         "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"ZC=F",  "name":"Mais Futures",              "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"ZW=F",  "name":"Weizen Futures",            "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"ZS=F",  "name":"Sojabohnen Futures",        "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
    {"ticker":"CC=F",  "name":"Kakao Futures",             "type":"commodity","category":"Rohstoffe","region":"GLOBAL"},
]

# Build search index
_INDEX = {}
for a in ASSETS:
    _INDEX[a["ticker"].upper()] = a
    for word in a["name"].lower().split():
        if word not in _INDEX:
            _INDEX[word] = []
        if isinstance(_INDEX[word], list):
            _INDEX[word].append(a)

def search(q: str, limit: int = 20) -> list:
    """Search assets by ticker or name."""
    q = q.strip()
    if not q:
        return []
    ql = q.lower()
    results = []
    seen = set()

    # Exact ticker match first
    if q.upper() in _INDEX and isinstance(_INDEX[q.upper()], dict):
        a = _INDEX[q.upper()]
        results.append(a)
        seen.add(a["ticker"])

    # Prefix match on ticker
    for a in ASSETS:
        if a["ticker"] not in seen and a["ticker"].upper().startswith(q.upper()):
            results.append(a)
            seen.add(a["ticker"])

    # Name contains
    for a in ASSETS:
        if a["ticker"] not in seen and ql in a["name"].lower():
            results.append(a)
            seen.add(a["ticker"])

    return results[:limit]

def get_by_category(category: str) -> list:
    return [a for a in ASSETS if a["category"] == category]

def get_categories() -> list:
    return sorted(set(a["category"] for a in ASSETS))

def get_by_ticker(ticker: str):
    return next((a for a in ASSETS if a["ticker"].upper() == ticker.upper()), None)
